package de.qaware.rookiecamp.sstdesign.ueb2.vorgabe.api.model;

import io.swagger.annotations.ApiModelProperty;

public class Beverage {
    @ApiModelProperty(value = "autogenerated id",required = true)
    private int beverageId;

    @ApiModelProperty(value = "name of the beverage type",required = true)
    private String type;


    public int getBeverageId() {
        return beverageId;
    }

    public void setBeverageId(int beverageId) {
        this.beverageId = beverageId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
