package de.qaware.rookiecamp.sstdesign.ueb2.vorgabe.api.model;

import io.swagger.annotations.ApiModelProperty;

public class Coffee {
    @ApiModelProperty(value="autogenerated")
    private int coffeeId;
    @ApiModelProperty(value="brand name of coffe",required = true)
    private String brand;
    @ApiModelProperty(value="image of the coffe package",required = false)
    private String imagePath;

    public int getCoffeeId() {
        return coffeeId;
    }

    public void setCoffeeId(int coffeeId) {
        this.coffeeId = coffeeId;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Coffee coffee = (Coffee) o;

        if (coffeeId != coffee.coffeeId) return false;
        if (brand != null ? !brand.equals(coffee.brand) : coffee.brand != null) return false;
        return imagePath != null ? imagePath.equals(coffee.imagePath) : coffee.imagePath == null;
    }

    @Override
    public int hashCode() {
        int result = coffeeId;
        result = 31 * result + (brand != null ? brand.hashCode() : 0);
        result = 31 * result + (imagePath != null ? imagePath.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "Coffee{" +
                "coffeeId=" + coffeeId +
                ", brand='" + brand + '\'' +
                ", imagePath='" + imagePath + '\'' +
                '}';
    }
}
